### ISSUE TITLE
Configuración

### ISSUE THREAD

**Issue by ghost** [Jimeno0/dotfiles#2]
Buenas, recién vi tu charla en Commit conf. Genial! Por favor, podrías explicar cómo aplicar tu dotfile en mi Vim! y luego cómo subir mi dotfile a mi repo. Gracias!

**Comment by Jimeno0** [comment]
👋 Sorry! no se como se me pudo pasar esto por completo:
1. Necesitas un plugin manager, en este caso yo utilizo [Plug](https://github.com/junegunn/vim-plug) mirate los pasos para instalarlo (es hyper sencillo)

2.  Clonarte el repo en tu raiz (por lo general `cd ~/`  y correr  el script para generar los symlinks dentro del repo una vez descargado ` bash makesymlinks.sh`

**Comment by ghost** [comment]
No pasa nada jaja. La primera parte ya está. A demás estuve mirando varios tutos. Te hago una pregunta: Qué es "una vez descargado `bash makesymlinks.sh`?

Gracias por la respuesta, tarde pero seguro! por cierto, muy buena tu explicación sobre Webpack.

**Comment by Jimeno0** [comment]
Me refiero a correr ese script, desde la terminal entra en el proyecto dotfiles y corre ese comando :)

**Comment by ghost** [comment]
Gracias!
